# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ip_port_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator

class Sever(object):
    def setupUi(self, MainWindow):
        self.onlyInt = QIntValidator()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(227, 150)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label_2.setObjectName("label_2")
        self.Btn_StartServer = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_StartServer.setGeometry(QtCore.QRect(130, 100, 91, 23))
        self.Btn_StartServer.setObjectName("Btn_StartServer")
        self.lineEdit_PortNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PortNumber.setGeometry(QtCore.QRect(80, 70, 141, 20))
        self.lineEdit_PortNumber.setObjectName("lineEdit_PortNumber")
        self.lineEdit_PortNumber.setValidator(self.onlyInt)
        rx = QtCore.QRegExp("[0-9]{5}")  # limit input string at most 5
        val = QtGui.QRegExpValidator(rx)  # +++
        self.lineEdit_PortNumber.setValidator(val)
        self.lineEdit_AETitle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_AETitle.setGeometry(QtCore.QRect(80, 10, 141, 20))
        self.lineEdit_AETitle.setObjectName("lineEdit_AETitle")
        self.lineEdit_IPAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_IPAddress.setGeometry(QtCore.QRect(80, 40, 141, 20))
        self.lineEdit_IPAddress.setObjectName("lineEdit_IPAddress")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 227, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AE Title:"))
        self.label_2.setText(_translate("MainWindow", "IP Address:"))
        self.Btn_StartServer.setText(_translate("MainWindow", "Start Server"))
        self.label_3.setText(_translate("MainWindow", "Port Number:"))
